auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: www.veyvin.com
url: http://www.veyvin.com
feed: /atom.xml
author_info: <a href="http://www.veyvin.com/">Veyvin</a>
