auto: true

markdown: rdiscount
rdiscount:
  extensions: [  "autolink", ]
pygments: true
paginate: 5
paginate_path: "projects/u3d/page:num"

markdown_ext:  markdown,mkd,mkdn,md
highlighter: pygments
exclude: [ "README.md",".idea",".iml",".name",".Node"]
encoding: "utf-8"

#在发布文章时使用一个未来的日期
future: true
#产生相关页面的索引
lsi:      false
#禁用定制插件
safe:     false

title: www.veyvin.com
url: http://www.veyvin.com
feed: /atom.xml
author_info: <a href="http://www.veyvin.com/">Veyvin</a>
